### PR TITLE
fix: default MUI override of body font-size

### LINKED ISSUE #78: SparkThemeProvider is overriding body font size to 0.875rem
image

Working on implementing the new Navbar into Prenda World and noticed that when wrapping the Navbar with the SparkThemeProvider, the font size for the body is being overwritten. Adding an `!important` to the body in main.less in Prenda World fixes this, but this seems like a deeper issue. 

Any thoughts on what's happening here? @WilliamKelley

### PR DESCRIPTION
**Pull request by WilliamKelley**
Closes #78

### CODE REVIEW

**Comment by WilliamKelley** [comment]
I'd like to have #77 merged first, need another review tho

**Comment by WilliamKelley** [comment]
Hm, this broke some styling, I need to do more work

File: libs/spark/src/theme/theme.ts [hunk 1]
```diff
@@ -92,6 +92,7 @@ declare module '@material-ui/core/styles/createPalette' {
 export const prendaTheme: ThemeOptions = {
   typography: {
     fontFamily: '"Nunito", Avenir, sans-serif',
+    fontSize: 1,
```
Comment (shadoath) [inline libs/spark/src/theme/theme.ts:95]: What is `1` referencing? Should this be `16` 
Or maybe better:
```
    htmlFontSize: 16,
``` 
or
```
    bodyFontSize: 16,
```

Comment (WilliamKelley) [reply libs/spark/src/theme/theme.ts:95]: Turns out it's pixels. I thought it was `rem` since it only accepts a number not a string (TS complains), but turns out the engine converts the px value to rem behind the scenes. We won't want to override `htmlFontSize` because of the a11y detriment noted on your link, but 16 is the correct value for `fontSize`

**Review by slingner — APPROVED** [review]

**Comment by WilliamKelley** [comment]
Looks a bunch of things get a bit bigger font size because of inheriting increase. I'll need to re-validate.

**Comment by WilliamKelley** [comment]
@shadoath fixed regressions

**Comment by WilliamKelley** [comment]
Added fix for additional issue noted in #78 about the CssBaseline defaults

**Comment by WilliamKelley** [comment]
They weren't actually regressions. 
- Typography: Accessory element margins changed very slightly, throwing off diff
- Colors: text font size inherited from body, not Typography component
- Icons: again, font size inherited from body -- i actually noticed these demos / components are wrong. They should use <SvgIcon> not <svg>... task for later

Good to go / review

File: libs/spark/src/theme/theme.ts [hunk 2]
```diff
@@ -92,10 +92,21 @@ declare module '@material-ui/core/styles/createPalette' {
...
+    body2: {
+      fontSize: 14,
+    },
   },
   overrides: {
     MuiCssBaseline: {
       '@global': {
+        body: {
+          fontFamily: '"Nunito", Avenir, sans-serif',
+          fontSize: 16,
```
Comment (shadoath) [inline libs/spark/src/theme/theme.ts:108]: Ahh so it was needed here too!

**Review by shadoath — APPROVED** [review]
